spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todo
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
    enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
logging:
  level:
    liquibase: DEBUG

